---
# Source: prometheus/templates/server-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: "master"
    app: prometheus
    release: prometheus-master
    chart: prometheus-8.11.2
    heritage: Tiller
  name: prometheus-master
spec:
  selector:
    matchLabels:
      component: "master"
      app: prometheus
      release: prometheus-master
  replicas: 1
  template:
    metadata:
      labels:
        component: "master"
        app: prometheus
        release: prometheus-master
        chart: prometheus-8.11.2
        heritage: Tiller
    spec:
      serviceAccountName: prometheus-master
      containers:
        - name: prometheus-master-configmap-reload
          image: "jimmidyson/configmap-reload:v0.2.2"
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9090/-/reload
          resources:
            {}
            
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true

        - name: prometheus-master
          image: "prom/prometheus:v2.8.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --storage.tsdb.retention.time=1h
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            {}
            
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: storage-volume
              mountPath: /data
              subPath: ""
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-master
        - name: storage-volume
          emptyDir:
            {}
