apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-sidecar
data:
  fluentd-sidecar.conf: "<source>\n  @type tail\n  path /tmp/log/ossp.log\n  pos_file
    /tmp/log/ossp.log.pos\n  tag ossp\n  <parse>\n    @type none\n  </parse>\n</source>\n\n<match
    **>\n  @id elasticsearch\n  @type elasticsearch\n  @log_level info\n  include_tag_key
    true\n  type_name _doc\n  host elasticsearch-master\n  port 9200\n  scheme http\n
    \ ssl_version TLSv1_2\n  ssl_verify true\n  logstash_format true\n  logstash_prefix
    logstash\n  reconnect_on_error true\n  <buffer>\n\t@type file\n\tpath /var/log/fluentd-buffers/kubernetes.system.buffer\n\tflush_mode
    interval\n\tretry_type exponential_backoff\n\tflush_thread_count 2\n\tflush_interval
    5s\n\tretry_forever\n\tretry_max_interval 30\n\tchunk_limit_size 2M\n\tqueue_limit_length
    8\n\toverflow_action block\n  </buffer>\n</match>\n"
